# Generated by Django 5.1.15 on 2026-07-04 23:59

import collab.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.CharField(default=collab.models._identity_id, max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('color', models.CharField(default=collab.models._random_color, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('step', models.JSONField()),
                ('client_id', models.CharField(max_length=64)),
                ('author_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='collab.document')),
            ],
            options={
                'ordering': ['version'],
                'unique_together': {('document', 'version')},
            },
        ),
    ]
