# Generated by Django 5.1.15 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='author_color',
            field=models.CharField(blank=True, default='#000000', max_length=16),
        ),
        migrations.AddField(
            model_name='step',
            name='author_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
